In [1]:
!pip install quantecon


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np
from numpy.linalg import eig
import scipy as sp
import quantecon as qe

In [3]:
A = np.array([[3, 2],
              [1, 4]])

# 计算特征值和右特征向量
λ, v = eig(A)

# 计算特征值和左特征向量
λ, w = eig(A.T)

# 保留5位小数
np.set_printoptions(precision=5)

print(f"A的特征值是:\n {λ}\n")
print(f"对应的右特征向量是: \n {v[:,0]} 和 {-v[:,1]}\n")
print(f"对应的左特征向量是: \n {w[:,0]} 和 {-w[:,1]}\n")

A的特征值是:
 [2. 5.]

对应的右特征向量是: 
 [-0.89443  0.44721] 和 [0.70711 0.70711]

对应的左特征向量是: 
 [-0.70711  0.70711] 和 [0.44721 0.89443]



In [4]:
eigenvals, ε, e = sp.linalg.eig(A, left=True)

print(f"A的特征值是:\n {eigenvals.real}\n")
print(f"对应的右特征向量是: \n {e[:,0]} 和 {-e[:,1]}\n")
print(f"对应的左特征向量是: \n {ε[:,0]} 和 {-ε[:,1]}\n")

A的特征值是:
 [2. 5.]

对应的右特征向量是: 
 [-0.89443  0.44721] 和 [0.70711 0.70711]

对应的左特征向量是: 
 [-0.70711  0.70711] 和 [0.44721 0.89443]



In [5]:
A = np.array([[0, 1, 0],
              [.5, 0, .5],
              [0, 1, 0]])

In [6]:
λ, v = eig(A)
principal_eigenvalue = np.max(np.abs(λ.real))
principal_eigenvector = v[:, np.argmax(np.abs(λ.real))]

principal_eigenvalue, principal_eigenvector

(1.0000000000000002, array([ 0.57735, -0.57735,  0.57735]))

In [7]:
print(np.dot(A, principal_eigenvector))
print(principal_eigenvalue * principal_eigenvector)

[-0.57735  0.57735 -0.57735]
[ 0.57735 -0.57735  0.57735]


In [8]:
A = np.array([[0, 1, 0],
              [0, 0, 0],
              [0, 0, 1]])
λ, v = eig(A)
principal_eigenvalue = np.max(np.abs(λ.real))
principal_eigenvector = v[:, np.argmax(np.abs(λ.real))]

principal_eigenvalue, principal_eigenvector

(1.0, array([0., 0., 1.]))

In [9]:
B = np.array([[0, 1, 1],
              [1, 0, 1],
              [1, 1, 0]])

np.linalg.matrix_power(B, 2)

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [10]:
np.linalg.matrix_power(B, 5)

array([[10, 11, 11],
       [11, 10, 11],
       [11, 11, 10]])

In [11]:
λ, v = eig(B)
_, w = eig(B.T)

principal_eigenvector_right = v[:, np.argmax(np.abs(λ.real))]
principal_eigenvector_left = w[:, np.argmax(np.abs(λ.real))]

P = np.outer(principal_eigenvector_right, principal_eigenvector_left)
P / np.sum(principal_eigenvector_right * principal_eigenvector_left)  # 归一化

array([[0.33333, 0.33333, 0.33333],
       [0.33333, 0.33333, 0.33333],
       [0.33333, 0.33333, 0.33333]])

In [12]:
m = 10
np.linalg.matrix_power(B / principal_eigenvalue, m)

array([[342., 341., 341.],
       [341., 342., 341.],
       [341., 341., 342.]])

In [13]:
def compute_perron_projection(M):

    eigval, v = eig(M)
    eigval, w = eig(M.T)

    r = np.max(eigval)

    # 找到主特征值的索引
    i = np.argmax(eigval)

    # 获取Perron特征向量
    v_P = v[:, i].reshape(-1, 1)
    w_P = w[:, i].reshape(-1, 1)

    # 归一化左、右特征向量
    norm_factor = w_P.T @ v_P
    v_norm = v_P / norm_factor

    # 计算Perron投影矩阵
    P = v_norm @ w_P.T
    return P, r

def check_convergence(M):
    P, r = compute_perron_projection(M)
    print("Perron投影矩阵:")
    print(P)

    # 定义 n 的取值列表
    n_list = [1, 10, 100, 1000, 10000]

    for n in n_list:

        # 计算 (A/r)^n
        M_n = np.linalg.matrix_power(M/r, n)

        # 计算 A^n / r^n 与 Perron投影的差异
        diff = np.abs(M_n - P)

        # 计算差异矩阵的范数
        diff_norm = np.linalg.norm(diff, 'fro')
        print(f"n = {n}, 误差 = {diff_norm:.10f}")

A1 = np.array([[1, 2],
               [1, 4]])

A2 = np.array([[0, 1, 1],
               [1, 0, 1],
               [1, 1, 0]])

A3 = np.array([[0.971, 0.029, 0.1, 1],
               [0.145, 0.778, 0.077, 0.59],
               [0.1, 0.508, 0.492, 1.12],
               [0.2, 0.8, 0.71, 0.95]])

for M in A1, A2, A3:
    print("矩阵:")
    print(M)
    check_convergence(M)
    print()
    print("-"*36)
    print()

矩阵:
[[1 2]
 [1 4]]
Perron投影矩阵:
[[0.1362  0.48507]
 [0.24254 0.8638 ]]
n = 1, 误差 = 0.0989045731
n = 10, 误差 = 0.0000000001
n = 100, 误差 = 0.0000000000
n = 1000, 误差 = 0.0000000000
n = 10000, 误差 = 0.0000000000

------------------------------------

矩阵:
[[0 1 1]
 [1 0 1]
 [1 1 0]]
Perron投影矩阵:
[[0.33333 0.33333 0.33333]
 [0.33333 0.33333 0.33333]
 [0.33333 0.33333 0.33333]]
n = 1, 误差 = 0.7071067812
n = 10, 误差 = 0.0013810679
n = 100, 误差 = 0.0000000000
n = 1000, 误差 = 0.0000000000
n = 10000, 误差 = 0.0000000000

------------------------------------

矩阵:
[[0.971 0.029 0.1   1.   ]
 [0.145 0.778 0.077 0.59 ]
 [0.1   0.508 0.492 1.12 ]
 [0.2   0.8   0.71  0.95 ]]
Perron投影矩阵:
[[0.12506 0.31949 0.20233 0.43341]
 [0.07714 0.19707 0.1248  0.26735]
 [0.12158 0.31058 0.19669 0.42133]
 [0.13885 0.3547  0.22463 0.48118]]
n = 1, 误差 = 0.5361031549
n = 10, 误差 = 0.0000434043
n = 100, 误差 = 0.0000000000
n = 1000, 误差 = 0.0000000000
n = 10000, 误差 = 0.0000000000

------------------------------------



In [14]:
B = np.array([[0, 1, 1],
              [1, 0, 0],
              [1, 0, 0]])

# 这表明矩阵不是初等的
print("矩阵:")
print(B)
print("B 的第100次方:")
print(np.linalg.matrix_power(B, 100))

check_convergence(B)

矩阵:
[[0 1 1]
 [1 0 0]
 [1 0 0]]
B 的第100次方:
[[1125899906842624                0                0]
 [               0  562949953421312  562949953421312]
 [               0  562949953421312  562949953421312]]
Perron投影矩阵:
[[0.5     0.35355 0.35355]
 [0.35355 0.25    0.25   ]
 [0.35355 0.25    0.25   ]]
n = 1, 误差 = 1.0000000000
n = 10, 误差 = 1.0000000000
n = 100, 误差 = 1.0000000000
n = 1000, 误差 = 1.0000000000
n = 10000, 误差 = 1.0000000000


In [15]:
P_hamilton = np.array([[0.971, 0.029, 0.000],
                       [0.145, 0.778, 0.077],
                       [0.000, 0.508, 0.492]])

print(compute_perron_projection(P_hamilton)[0])

[[0.8128  0.16256 0.02464]
 [0.8128  0.16256 0.02464]
 [0.8128  0.16256 0.02464]]


In [16]:
mc = qe.MarkovChain(P_hamilton)
ψ_star = mc.stationary_distributions[0]
ψ_star

array([0.8128 , 0.16256, 0.02464])

In [17]:
# 定义两个随机矩阵
P1 = np.array([[0.5, 0.2, 0.3],
               [0.3, 0.5, 0.2],
               [0.4, 0.1, 0.5]])

P2 = np.array([[0.6, 0.4],
               [0.4, 0.6]])

In [18]:
λ1, v1 = eig(P1)
λ2, v2 = eig(P2)

w1 = v1[:, np.argmax(λ1.real)]
w2 = v2[:, np.argmax(λ2.real)]

print(f"P1 的主特征值 λ: {λ1[np.argmax(λ1.real)]}")
print(f"P1 的主右特征向量 w: {w1}")

print(f"P2 的主特征值 λ: {λ2[np.argmax(λ2.real)]}")
print(f"P2 的主右特征向量 w: {w2}")

P1 的主特征值 λ: 0.9999999999999999
P1 的主右特征向量 w: [-0.57735 -0.57735 -0.57735]
P2 的主特征值 λ: 1.0
P2 的主右特征向量 w: [0.70711 0.70711]


In [19]:
ψ1_star = w1 / np.sum(w1)
ψ2_star = w2 / np.sum(w2)

print(f"P1 的平稳分布 ψ* : {ψ1_star}")
print(f"P2 的平稳分布 ψ* : {ψ2_star}")

P1 的平稳分布 ψ* : [0.33333 0.33333 0.33333]
P2 的平稳分布 ψ* : [0.5 0.5]


In [20]:
A = np.array([[0.3, 0.2, 0.3],
              [0.2, 0.4, 0.3],
              [0.2, 0.5, 0.1]])

evals, evecs = eig(A)

r = max(abs(λ) for λ in evals)   #主特征值/谱半径
print(r)

0.8444086477164563


In [21]:
I = np.identity(3)
B = I - A

d = np.array([4, 5, 12])
d.shape = (3,1)

B_inv = np.linalg.inv(B)
x_star = B_inv @ d
print(x_star)

[[38.30189]
 [44.33962]
 [46.47799]]
