In [1]:
!pip install graphviz quantecon

In [2]:
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import eig
import scipy as sp
import graphviz as gv
import quantecon as qe

In [3]:
A = np.array([[3, 2], 
              [1, 4]])

# Compute right eigenvectors and eigenvalues
λ_r, v = eig(A)

# Compute left eigenvectors and eigenvalues
λ_l, w = eig(A.T)

print("Right Eigenvalues:")
print(λ_r)
print("\nRight Eigenvectors:")
print(v)
print("\nLeft Eigenvalues:")
print(λ_l)
print("\nLeft Eigenvectors:")
print(w)

Right Eigenvalues:
[2. 5.]

Right Eigenvectors:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]

Left Eigenvalues:
[2. 5.]

Left Eigenvectors:
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


In [4]:
eigenvals, ε, e = sp.linalg.eig(A, left=True)

print("Right Eigenvalues:")
print(λ_r)
print("\nRight Eigenvectors:")
print(v)
print("\nLeft Eigenvalues:")
print(λ_l)
print("\nLeft Eigenvectors:")
print(w)

Right Eigenvalues:
[2. 5.]

Right Eigenvectors:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]

Left Eigenvalues:
[2. 5.]

Left Eigenvectors:
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


In [5]:
A = np.array([[0, 1, 0], 
              [.5, 0, .5], 
              [0, 1, 0]])

In [6]:
eig(A)

(array([-1.00000000e+00, -3.30139063e-18,  1.00000000e+00]),
 array([[ 5.77350269e-01,  7.07106781e-01,  5.77350269e-01],
        [-5.77350269e-01,  2.95712306e-18,  5.77350269e-01],
        [ 5.77350269e-01, -7.07106781e-01,  5.77350269e-01]]))

In [7]:
B = np.array([[0, 1, 1], 
              [1, 0, 1], 
              [1, 1, 0]])

np.linalg.matrix_power(B, 2)

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [8]:
num_iters = 20
b = np.random.rand(B.shape[1])

for i in range(num_iters):
    b = B @ b
    b = b / np.linalg.norm(b)

dominant_eigenvalue = np.dot(B @ b, b) / np.dot(b, b)
np.round(dominant_eigenvalue, 2)

2.0

In [9]:
eig(B)

(array([-1.,  2., -1.]),
 array([[-0.81649658,  0.57735027, -0.27880153],
        [ 0.40824829,  0.57735027, -0.5252061 ],
        [ 0.40824829,  0.57735027,  0.80400763]]))

In [10]:
def compute_perron_projection(M):

    eigval, v = eig(M)
    eigval, w = eig(M.T)

    r = np.max(eigval)

    # Find the index of the dominant (Perron) eigenvalue
    i = np.argmax(eigval)

    # Get the Perron eigenvectors
    v_P = v[:, i].reshape(-1, 1)
    w_P = w[:, i].reshape(-1, 1)

    # Normalize the left and right eigenvectors
    norm_factor = w_P.T @ v_P
    v_norm = v_P / norm_factor

    # Compute the Perron projection matrix
    P = v_norm @ w_P.T
    return P, r

def check_convergence(M):
    P, r = compute_perron_projection(M)
    print("Perron projection:")
    print(P)

    # Define a list of values for n
    n_list = [1, 10, 100, 1000, 10000]

    for n in n_list:
        
        # Compute (A/r)^n
        M_n = np.linalg.matrix_power(M/r, n)

        # Compute the difference between A^n / r^n and the Perron projection
        diff = np.abs(M_n - P)

        # Calculate the norm of the difference matrix
        diff_norm = np.linalg.norm(diff, 'fro')
        print(f"n = {n}, norm of the difference: {diff_norm:.10f}")


A1 = np.array([[1, 2],
               [1, 4]])

A2 = np.array([[0, 1, 1], 
              [1, 0, 1], 
              [1, 1, 0]])

A3 = np.array([[0.971, 0.029, 0.1, 1],
               [0.145, 0.778, 0.077, 0.59],
               [0.1, 0.508, 0.492, 1.12],
               [0.2, 0.8, 0.71, 0.95]])

for M in A1, A2, A3:
    print("Matrix:")
    print(M)
    check_convergence(M)
    print()
    print("-"*36)
    print()

Matrix:
[[1 2]
 [1 4]]
Perron projection:
[[0.13619656 0.48507125]
 [0.24253563 0.86380344]]
n = 1, norm of the difference: 0.0989045731
n = 10, norm of the difference: 0.0000000001
n = 100, norm of the difference: 0.0000000000
n = 1000, norm of the difference: 0.0000000000
n = 10000, norm of the difference: 0.0000000000

------------------------------------

Matrix:
[[0 1 1]
 [1 0 1]
 [1 1 0]]
Perron projection:
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
n = 1, norm of the difference: 0.7071067812
n = 10, norm of the difference: 0.0013810679
n = 100, norm of the difference: 0.0000000000
n = 1000, norm of the difference: 0.0000000000
n = 10000, norm of the difference: 0.0000000000

------------------------------------

Matrix:
[[0.971 0.029 0.1   1.   ]
 [0.145 0.778 0.077 0.59 ]
 [0.1   0.508 0.492 1.12 ]
 [0.2   0.8   0.71  0.95 ]]
Perron projection:
[[0.12506189 0.31948872 0.20232606 0.43340956]
 [0.07714374 0.1970748

In [11]:
B = np.array([[0, 1, 1], 
              [1, 0, 0], 
              [1, 0, 0]])

# This shows that the matrix is not primitive
print("Matrix:")
print(B)
print("100th power of matrix B:")
print(np.linalg.matrix_power(B, 100))

check_convergence(B)

Matrix:
[[0 1 1]
 [1 0 0]
 [1 0 0]]
100th power of matrix B:
[[1125899906842624                0                0]
 [               0  562949953421312  562949953421312]
 [               0  562949953421312  562949953421312]]
Perron projection:
[[0.5        0.35355339 0.35355339]
 [0.35355339 0.25       0.25      ]
 [0.35355339 0.25       0.25      ]]
n = 1, norm of the difference: 1.0000000000
n = 10, norm of the difference: 1.0000000000
n = 100, norm of the difference: 1.0000000000
n = 1000, norm of the difference: 1.0000000000
n = 10000, norm of the difference: 1.0000000000


In [12]:
P = np.array([[0.68, 0.12, 0.20],
              [0.50, 0.24, 0.26],
              [0.36, 0.18, 0.46]])

print(compute_perron_projection(P)[0])

[[0.56145769 0.15565164 0.28289067]
 [0.56145769 0.15565164 0.28289067]
 [0.56145769 0.15565164 0.28289067]]


In [13]:
mc = qe.MarkovChain(P)
ψ_star = mc.stationary_distributions[0]
ψ_star

array([0.56145769, 0.15565164, 0.28289067])

In [14]:
P_hamilton = np.array([[0.971, 0.029, 0.000],
                       [0.145, 0.778, 0.077],
                       [0.000, 0.508, 0.492]])

print(compute_perron_projection(P_hamilton)[0])

[[0.8128  0.16256 0.02464]
 [0.8128  0.16256 0.02464]
 [0.8128  0.16256 0.02464]]


In [15]:
mc = qe.MarkovChain(P_hamilton)
ψ_star = mc.stationary_distributions[0]
ψ_star

array([0.8128 , 0.16256, 0.02464])

In [16]:
A = np.array([[0.4, 0.1],
              [0.7, 0.2]])

evals, evecs = eig(A)   # finding eigenvalues and eigenvectors

r = max(abs(λ) for λ in evals)    # compute spectral radius
print(r)

0.5828427124746189


In [17]:
I = np.identity(2)      #2 x 2 identity matrix
B = I - A

In [18]:
B_inverse = np.linalg.inv(B)     #direct inverse method

In [19]:
A_sum = np.zeros((2,2))        #power series sum of A
A_power = I
for i in range(50):
    A_sum += A_power
    A_power = A_power @ A

In [20]:
np.allclose(A_sum, B_inverse)     

True

In [21]:
A = np.array([[0.3, 0.2, 0.3],
              [0.2, 0.4, 0.3],
              [0.2, 0.5, 0.1]])

evals, evecs = eig(A)

r = max(abs(λ) for λ in evals)   #dominant eigenvalue/spectral radius
print(r)

0.8444086477164554


In [22]:
I = np.identity(3)
B = I - A

d = np.array([4, 5, 12])
d.shape = (3,1)

B_inv = np.linalg.inv(B)
x_star = B_inv @ d
print(x_star)

[[38.30188679]
 [44.33962264]
 [46.47798742]]
